//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gitea.VisualStudio.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gitea.VisualStudio.Shared.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After created open  in the browser.
        /// </summary>
        public static string AfterCreatedOpenInTheBrowser {
            get {
                return ResourceManager.GetString("AfterCreatedOpenInTheBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        public static string CloneView_FailedToLoadProjects {
            get {
                return ResourceManager.GetString("CloneView_FailedToLoadProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects.
        /// </summary>
        public static string CloneView_NoProjects {
            get {
                return ResourceManager.GetString("CloneView_NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string CloneView_Search {
            get {
                return ResourceManager.GetString("CloneView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a .gitignore.
        /// </summary>
        public static string Common_ChooseAGitIgnore {
            get {
                return ResourceManager.GetString("Common_ChooseAGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a license.
        /// </summary>
        public static string Common_ChooseALicense {
            get {
                return ResourceManager.GetString("Common_ChooseALicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string Common_Clone {
            get {
                return ResourceManager.GetString("Common_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Common_CreateRepository {
            get {
                return ResourceManager.GetString("Common_CreateRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Local.
        /// </summary>
        public static string Common_DeleteLocal {
            get {
                return ResourceManager.GetString("Common_DeleteLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of description is 500.
        /// </summary>
        public static string Common_DescriptionMaxTo {
            get {
                return ResourceManager.GetString("Common_DescriptionMaxTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git ignore.
        /// </summary>
        public static string Common_GitIgnore {
            get {
                return ResourceManager.GetString("Common_GitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Common_License {
            get {
                return ResourceManager.GetString("Common_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Common_Message {
            get {
                return ResourceManager.GetString("Common_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of name is 64 chars.
        /// </summary>
        public static string Common_NameMaxTo {
            get {
                return ResourceManager.GetString("Common_NameMaxTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Common_New {
            get {
                return ResourceManager.GetString("Common_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Common_Open {
            get {
                return ResourceManager.GetString("Common_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Common_Owner {
            get {
                return ResourceManager.GetString("Common_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Common_Path {
            get {
                return ResourceManager.GetString("Common_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Common_Private {
            get {
                return ResourceManager.GetString("Common_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Common_Property {
            get {
                return ResourceManager.GetString("Common_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Common_Quit {
            get {
                return ResourceManager.GetString("Common_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        public static string Confirm_Quit {
            get {
                return ResourceManager.GetString("Confirm_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateSnippet_Button {
            get {
                return ResourceManager.GetString("CreateSnippet_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no title.
        /// </summary>
        public static string CreateSnippetNoTitle {
            get {
                return ResourceManager.GetString("CreateSnippetNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code IsRequired.
        /// </summary>
        public static string CreateSnippetViewModel_CodeIsRequired {
            get {
                return ResourceManager.GetString("CreateSnippetViewModel_CodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptors Is Required.
        /// </summary>
        public static string CreateSnippetViewModel_DescriptorsIsRequired {
            get {
                return ResourceManager.GetString("CreateSnippetViewModel_DescriptorsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Snippet.
        /// </summary>
        public static string CreateSnippetViewModel_FailedToCreateSnippet {
            get {
                return ResourceManager.GetString("CreateSnippetViewModel_FailedToCreateSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName Is Required.
        /// </summary>
        public static string CreateSnippetViewModel_FileNameIsRequired {
            get {
                return ResourceManager.GetString("CreateSnippetViewModel_FileNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Is Required.
        /// </summary>
        public static string CreateSnippetViewModel_TitleIsRequired {
            get {
                return ResourceManager.GetString("CreateSnippetViewModel_TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Is Required.
        /// </summary>
        public static string CreateSnippetViewModel_VisibilityIsRequired {
            get {
                return ResourceManager.GetString("CreateSnippetViewModel_VisibilityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is mandatory.
        /// </summary>
        public static string CreateView_NameIsRequired {
            get {
                return ResourceManager.GetString("CreateView_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is mandatory.
        /// </summary>
        public static string CreateView_PathIsRequired {
            get {
                return ResourceManager.GetString("CreateView_PathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a cool project (optional).
        /// </summary>
        public static string CreateView_ThisIsACoollProject {
            get {
                return ResourceManager.GetString("CreateView_ThisIsACoollProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project {0} already exists!.
        /// </summary>
        public static string CreateViewModel_OnSave_TheProject0AlreadyExists {
            get {
                return ResourceManager.GetString("CreateViewModel_OnSave_TheProject0AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://giteahub.com/.
        /// </summary>
        public static string DefaultHost {
            get {
                return ResourceManager.GetString("DefaultHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git with a cup of tea!.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blame.
        /// </summary>
        public static string GitAnalysis_Blame {
            get {
                return ResourceManager.GetString("GitAnalysis_Blame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commits.
        /// </summary>
        public static string GitAnalysis_Commits {
            get {
                return ResourceManager.GetString("GitAnalysis_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... (Full ID).
        /// </summary>
        public static string GitAnalysis_GetGiteaTargetDescription_FullID {
            get {
                return ResourceManager.GetString("GitAnalysis_GetGiteaTargetDescription_FullID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision: .
        /// </summary>
        public static string GitAnalysis_Revision {
            get {
                return ResourceManager.GetString("GitAnalysis_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch: .
        /// </summary>
        public static string GitAnalysisn_Branch {
            get {
                return ResourceManager.GetString("GitAnalysisn_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Login .
        /// </summary>
        public static string GiteaInvitationSection_GiteaInvitationSection_NoLogin {
            get {
                return ResourceManager.GetString("GiteaInvitationSection_GiteaInvitationSection_NoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Invitation_Connect {
            get {
                return ResourceManager.GetString("Invitation_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Invitation_SignUp {
            get {
                return ResourceManager.GetString("Invitation_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Items_Issues {
            get {
                return ResourceManager.GetString("Items_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulls Requests.
        /// </summary>
        public static string Items_MergeRequests {
            get {
                return ResourceManager.GetString("Items_MergeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipelines.
        /// </summary>
        public static string Items_Pipeline {
            get {
                return ResourceManager.GetString("Items_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string Items_Wiki {
            get {
                return ResourceManager.GetString("Items_Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to {0}.
        /// </summary>
        public static string Login_ConnectTo {
            get {
                return ResourceManager.GetString("Login_ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name or Email .
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string Login_EmailIsInvalid {
            get {
                return ResourceManager.GetString("Login_EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is mandatory.
        /// </summary>
        public static string Login_EmailIsRequired {
            get {
                return ResourceManager.GetString("Login_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        public static string Login_FailedToLogin {
            get {
                return ResourceManager.GetString("Login_FailedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiteaHub(https://giteahub.com/).
        /// </summary>
        public static string Login_Host {
            get {
                return ResourceManager.GetString("Login_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is invalid.
        /// </summary>
        public static string Login_HostIsInvalid {
            get {
                return ResourceManager.GetString("Login_HostIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is mandatory.
        /// </summary>
        public static string Login_PasswordIsRequired {
            get {
                return ResourceManager.GetString("Login_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should at least be 6 chars.
        /// </summary>
        public static string Login_PasswordMinTo {
            get {
                return ResourceManager.GetString("Login_PasswordMinTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resent email to active account.
        /// </summary>
        public static string Login_ReSendEmail {
            get {
                return ResourceManager.GetString("Login_ReSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gitea.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Snippet.
        /// </summary>
        public static string OpenOnGiteaPackage_CreateSnippet {
            get {
                return ResourceManager.GetString("OpenOnGiteaPackage_CreateSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gitea.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Publish_Login {
            get {
                return ResourceManager.GetString("Publish_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Publish_Or {
            get {
                return ResourceManager.GetString("Publish_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish_Publish {
            get {
                return ResourceManager.GetString("Publish_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Publish_SignUp {
            get {
                return ResourceManager.GetString("Publish_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Publish_Start {
            get {
                return ResourceManager.GetString("Publish_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting.
        /// </summary>
        public static string Publish_Submiting {
            get {
                return ResourceManager.GetString("Publish_Submiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to {0}.
        /// </summary>
        public static string Publish_Title {
            get {
                return ResourceManager.GetString("Publish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        public static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Repository_Name {
            get {
                return ResourceManager.GetString("Repository_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Authentication.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not login yet.
        /// </summary>
        public static string WebService_CreateProject_NotLoginYet {
            get {
                return ResourceManager.GetString("WebService_CreateProject_NotLoginYet", resourceCulture);
            }
        }
    }
}
