// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gitea.VisualStudio
{
    static class Vsix
    {
        public const string Id = "62991164-1F3E-4AAA-BF2F-537C83AF987C";
        public const string Name = "Gitea Extension for Visual Studio";
        public const string Description = @"A Visual Studio Extension that brings the Gitea Flow into Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "MysticBoy";
        public const string Tags = "Gitea;git;open source;source control;branch;Pipelines;Registry;Graphs;IssuesMerge Requests;Wiki";
    }
}
